# https://lefthook.dev/configuration/

commit-msg:
  jobs:
    - name: commitlint
      run: bunx commitlint --edit {1}

pre-commit:
  parallel: true
  jobs:
    - name: ESLint
      run: bun lint:scripts
      glob: '*.ts'

    - name: Stylelint
      run: bun lint:styles
      glob:
        - '*.scss'

pre-push:
  jobs:
    - name: Packages audit
      run: bun run audit --audit-level=moderate
      glob:
        - package.json
        - bun.lock
