name: nnda's personal website

sources:
  npm: true

allowed:
  - mit
  - ofl-1.1
  - cc0-1.0

reviewed:
  npm:
    - '@fortawesome/fontawesome-common-types'
    - '@fortawesome/fontawesome-svg-core'
    - '@fortawesome/free-regular-svg-icons'
    - '@fortawesome/free-solid-svg-icons'
