name: Deployment


on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.py'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.scss'
      - '**/*.hbs'
      - 'src/'
      - '.github/workflows/deploy.yml'
      - 'bun.lock'
      - 'package.json'
      - 'config/tsconfig.*.json'
      - 'config/webpack.common.ts'
      - 'config/webpack.config.ts'
      - 'config/wrangler.toml'
      - 'config/requirements.txt'
      - 'config/Dockerfile'
  workflow_dispatch:


jobs:
  check-pip: # ----------------------------------------------------------------
    name: Check pip/requirements.txt

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0
        with:
          sparse-checkout: |
            config/requirements.txt
          sparse-checkout-cone-mode: false

      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: config/requirements.txt


  check-bun: # ----------------------------------------------------------------
    name: Check Bun/package.json

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0
        with:
          sparse-checkout: |
            .github/actions/setup-bun/action.yml
            bun.lock
            package.json
          sparse-checkout-cone-mode: false

      - uses: ./.github/actions/setup-bun
        with:
          cache: no
          install-deps: no

      - name: Audit Bun dependencies
        run: |
          bun audit --audit-level moderate


  deps-changes: # -------------------------------------------------------------
    name: Dependency changes
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.filter.outputs.deps }}

    steps:
      - uses: actions/checkout@v7.0.0
      - uses: dorny/paths-filter@v4.0.1
        id: filter
        with:
          filters: |
            deps:
            - 'config/Dockerfile'
            - 'config/requirements.txt'
            - 'package.json'
            - 'bun.lock'


  docker-image: # -------------------------------------------------------------
    name: Build & push Docker image
    if: |
      ${{
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&

        needs.deps-changes.outputs.changed == 'true'
      }}

    needs:
      - check-bun
      - check-pip
      - deps-changes

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/build-docker-image
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}


  deploy: # -------------------------------------------------------------------
    name: Deploy to Cloudflare

    runs-on: ubuntu-latest

    if: |
      ${{
        always() &&
        needs.deps-changes.result == 'success' &&
        (
          needs.docker-image.result == 'success' ||
          needs.docker-image.result == 'skipped'
        )
      }}

    needs:
      - check-bun
      - check-pip
      - deps-changes
      - docker-image

    container:
      image: nndda/nnda.dev:latest
      credentials:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v7.0.0
      - name: Build website
        run: |
          cp -arT . /nnda.dev
          cd /nnda.dev

          git config --global --add safe.directory /nnda.dev

          python -m venv .
          source bin/activate

          bun run build

          cp config/wrangler.toml .

        shell: bash
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_PAT_EXT: ${{ secrets.GH_PAT_EXT }}
          SITE_EXT: ${{ secrets.SITE_EXT }}
          COMMIT_SHA: ${{ github.sha }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --commit-dirty=true --project-name nnda /nnda.dev/dist/
