name: Stylelint

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.scss'
      - '**/*.css'
      - '.github/workflows/lint-styles.yml'
      - 'config/.stylelintrc.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.scss'
      - '**/*.css'
      - '.github/workflows/lint-styles.yml'
      - 'config/.stylelintrc.json'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache linting dependencies
        id: stylelint-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-stylelint

      - name: Install linting dependencies
        run: |
          npm install --no-save \
            stylelint \
            stylelint-config-standard-scss

      - name: Lint stylesheets
        run: npm run lint:styles
