name: Stylelint

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.scss'
      - '**/*.css'
      - '.github/workflows/lint-styles.yml'
      - 'config/.stylelintrc.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.scss'
      - '**/*.css'
      - '.github/workflows/lint-styles.yml'
      - 'config/.stylelintrc.json'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - uses: ./.github/actions/setup-bun

      - name: Lint stylesheets
        run: bun run lint:styles
